### ISSUE TITLE
Integrate codacy (or an other code quality tool) into the repository

### ISSUE THREAD

**Issue by FedorSmirnov89** [felixreimann/opt4j#19]

**Comment by felixreimann** [comment]
It might be useful to have a checkstyle config for this task. I once created one which resembles our eclipse formatter configs quite well (based on google's checkstyle config). Maybe, you need it for the settings of codacy. You find it in branch feature/checkstyle.

**Comment by felixreimann** [comment]
https://github.com/felixreimann/opt4j/pull/24
