### ISSUE TITLE
Address codacy issues across the project

### ISSUE THREAD

**Issue by michaelhglass** [felixreimann/opt4j#35]
After the codacy integration, I suggest a round of patching all across the project.

**Comment by FedorSmirnov89** [comment]
Don't you think we should start by writing tests for the classes? I think that a substantial refactoring is quite likely to introduce a lot of small mistakes that we may not see without tests.

**Comment by michaelhglass** [comment]
At this point, I only addressed style issues that should (in the best case) not change the code significantly and should be doable via code-review. At least my 2cc. The one mistake caught by Felix was in fact a dumb mistake by me, but spotting a line changing from w1 != w0 to w1 == w0 is what we have code review for, right?

**Comment by FedorSmirnov89** [comment]
I just mean that in the long run, we have to both write tests and address the issues anyway. And having tests makes refactoring very comfortable

**Comment by michaelhglass** [comment]
Current issues solved. Further discussion in #39.
